// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fall back to the project's public URL / a harmless placeholder key when the
// build env doesn't provide them (e.g. a static GitHub Pages build without
// Supabase secrets). Use `||` (not `??`) so an empty-string env var — which is
// what CI passes for an unset secret — also falls back instead of being handed
// to createClient, which throws on an empty key and white-screens the app.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://hfwhwmkhkvlxkgkrvrpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "public-anon-key-unset";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});